### ISSUE TITLE
Problem with Hebrew and Arabic 

### ISSUE THREAD

**Issue by Perezari** [caesiumstudio/csBooks-updates#11]
hey,
Awesome program,
can you please fix the problem with Hebrew?
when im open a pdf file from the program the Hebrew shown as gibberish.
thanks. 

![csBooks_SH9GYKan5q](https://user-images.githubusercontent.com/24621247/110296017-7d8ee380-7ffa-11eb-8451-c94c5c3cca5a.png)

**Comment by caesiumstudio** [comment]
Hey Perezari, 
Thank you for reporting the issue. 
Could you please attach a sample book page that you are opening because I have no books in hebrew so would be helpful to have a real sample where the problem is occurring.

**Comment by caesiumstudio** [comment]
Closing because of no response from reporter.

**Comment by Perezari** [comment]
[2.pdf](https://github.com/caesiumstudio/csBooks-updates/files/7030978/2.pdf)
