### ISSUE TITLE
Does CS Books support DjVu?

### ISSUE THREAD

**Issue by mohammedbelgoumri** [caesiumstudio/csBooks-updates#13]
[question]/[feature request]

**Comment by caesiumstudio** [comment]
Hey Mohammed, 
Right now csBooks doesn't support DjVu. 
But I am planning to add more formats in the upcoming release.

**Comment by mohammedbelgoumri** [comment]
Thanks for the response; and the great work.

**Comment by caesiumstudio** [comment]
Feature implemented in version 6.1.0
