### ISSUE TITLE
Javascript error occurred in the main process

### ISSUE THREAD

**Issue by xandark** [caesiumstudio/csBooks-updates#2]
This looks really cool. I just installed it on my other KDE neon laptop, and after launching it for the first time and selecting my EBooks folder, I saw this error:

![Screenshot 2020-12-06 (14∶47∶38)](https://user-images.githubusercontent.com/5048913/101295404-5a258400-37d2-11eb-8345-a28a4f1e0bc8.png)

This is my system:

Operating System: KDE neon 5.20
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.1
Kernel Version: 5.4.0-56-generic
OS Type: 64-bit

**Comment by caesiumstudio** [comment]
Thanks for reporting the issue.
Could you please confirm if it is a problem specifically with this folder or is it not working for any other folder at all? 
And also which format of books do you have in the folder?

**Comment by xandark** [comment]
Hi Ravi,

I just figured out what is causing the import failure. In my folder I have a symlink to another disk, but this disk isn't mounted. So the symlink'd folder is

**Comment by xandark** [comment]
Sorry, I accidentally clicked the Close button. 

When I deleted the unreference-able symlink, csBooks doesn't show that message anymore. However I found another issue, which I'll create a new thread for.

To test this, I'd just create a symlink to a folder, and then modify the symlink's pointer to point to a non-existant place. Then re-run the import and you should get the crash I saw.

**Comment by caesiumstudio** [comment]
This is great! So I am going to simulate the symlink situation on my kde neon laptop and then fix it.

**Comment by caesiumstudio** [comment]
Fixed in release 4.3.3
https://github.com/caesiumstudio/csBooks-updates/tree/4.3.3

**Comment by xandark** [comment]
I can confirm that this seems to be fixed.
