### ISSUE TITLE
Is there a macOS version? I don't see a .dmg file on the Release page

### ISSUE THREAD

**Issue by chaostang** [caesiumstudio/csBooks-updates#23]

**Comment by caesiumstudio** [comment]
Uploaded the mac build of latest version. Please let me know if you face any problems or have some suggestions.

**Comment by pa-0** [comment]
Was the macOS version removed?

**Comment by caesiumstudio** [comment]
Hello Peter, 
I think there is some issue. Let me reupload the latest version. 
I will update you here after I have uploaded the version.

**Comment by caesiumstudio** [comment]
I uploaded it now. Please let me know if everything is working. Thank you for using csBooks :)
