### ISSUE TITLE
mac: “csBooks” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by letitfly** [caesiumstudio/csBooks-updates#24]
on Mac OS Ventura 13.0.1

**Comment by letitfly** [comment]
it could be a non issue since I can force open it in the settings. But it would be better to fix it.

**Comment by caesiumstudio** [comment]
As the distribution of csBooks is not through a registered channel of Apple, it is a way for apple to make customers aware of potential risks. Feel free to add exceptions in your settings as "csBooks" is totally safe software. :)
