### ISSUE TITLE
The pages are out of order

### ISSUE THREAD

**Issue by retRower** [caesiumstudio/csBooks-updates#26]
Hi!

I just bought your product and I really like it! I just wanted to be comfortable using my books in e-pub form, and you are providing that with really great quality, great! I am grateful for that.
The only problem is that the pages are shifted. I mean, for example, I have more than 10 books in English on the left and Turkish on the right page. So, I can compare the words on the left side of my books with those on the right. However, in your application, the pages are not displayed as left and right, but one page ahead. Please let me explain with photo:
Must be like this:
[https://www.turengkitap.com/wp-content/uploads/2022/02/turkce-cevirili-ingilizce-hikaye.jpg](url)

But its pages look like this on app:
[https://imgur.com/a/16Fy4Az](url)

Even-numbered pages should be on the left, odd-numbered pages should be on the right. But this is not the case unfortunately.

How can I fix this? I must move the even-numbered pages to the left, or delete a page from the book. Please help me

Regards,
Berk T.

**Comment by caesiumstudio** [comment]
Hello, is it possible to provide a sample book. Then I can test it and fix it.

**Comment by retRower** [comment]
I'm still waiting for help. Can you please help?

**Comment by caesiumstudio** [comment]
As Epub book is a free-flowing format, it is not possible to provide a fix page option. You can try to adjust the font size/style/margin etc.. but a fixed left-right behavior is not what EPUB format is made to do. Without a book sample, it is not possible to try to fix it.

**Comment by retRower** [comment]
Okay, I got permission for the books that I couldn't send due to copyright reasons. Now I am sending you 1 as an example. Can you solve the scrolling problem on the pages?
I cannot upload files with epub extension directly here. Therefore, I uploaded 2 books exactly to one download link:
https://u.pcloud.link/publink/show?code=kZs5aDVZLXp1KoqtOTm9H0kUO3OC3SSmi4qk

**Comment by retRower** [comment]
I'm still waiting for help. Can you please help?

**Comment by caesiumstudio** [comment]
Implemented in 7.4.0. Submitted to Microsoft Store, it might take some time until available for update.

**Comment by retRower** [comment]
First of all, thank you for your interest and help! I was constantly waiting for your update to be released, and I just (finally!) downloaded your update.

Unfortunately, you did not fully understand our problem. As I told you before: The problem was not changing the position of the pages, the problem is we must scrolling the pages. I mean please look at this photo, this is the current state (must be fixed):

https://imgur.com/M5rGZUU

BUT, As in the original of the book and all other e-pub applications, the pages should actually look like this (it should be, the correct version):
https://imgur.com/v9SPrQX

Do you see the words coming together? Thus, there are identical lines on the left and right sides of the book. They just belong to different languages. So it wasn't to make pages 6-5 instead of 5-6 (that's how you did it). What was asked of you was that you could do 6-7 instead of 5-6.

You see the matching words between the two pages, right? Thus, there are identical lines on the left and right sides of the book. They just belong to different languages. So it wasn't to make pages 6-5 instead of 5-6 (that's how you did it). What was asked of you was that you could do 6-7 instead of 5-6.

Pages appear one page ahead in csbooks app unfortunately. All we wanted was to go back 1 page and see the English-Turkish sentences coming together.
Despite all this, it is really admirable that you took the time to update us. Thank you very much and more: If you can implement these changes, I will personally introduce your application to hundreds of people in Turkey so that they can use the Turkish equivalents of English books! In this way, they will see that you work for us and strive for us, and they will use csbooks for translation books!

Although it is not what we wanted, but I want to say thank you again for your efforts, we are really grateful for that.

**Comment by caesiumstudio** [comment]
Hey RetRower, 
I implemented now single page scroll.. Please see this video and let me know if this satisfies your needs. 
https://www.youtube.com/watch?v=LlYCu6q6i3A

**Comment by retRower** [comment]
Brilliant! This is exactly what we wanted and expected! Please do this!

**Comment by caesiumstudio** [comment]
Thanks for feedback. Now it should be available to download from MS Store in few hours.
