### ISSUE TITLE
Installation on Manjaro or Arch fails

### ISSUE THREAD

**Issue by bennyzen** [caesiumstudio/csBooks-updates#27]
Just tried to install this excellent book manager/reader under Manjaro using the builtin package manager and it unfortunately fails. Haven't investigated it any further what exactly is the cause, but I suspect the path to the GitHub download is just wrong and points to nowhere. Keep up your good work on this one.

I just installed it by downloading the pacman package provided here and doing something like `sudo pacman -U ./csBooks-7.5.0.pacman`. Then it works flawlessly.

**Comment by caesiumstudio** [comment]
Could you please provide more details about the Manjaro OS. Which version are you using and which Desktop?Environment?

**Comment by caesiumstudio** [comment]
I tested and it is not installable with the package manager as you suggested. Please provide any information you can find out.. that will be really helpful in providing a solution for more users.

**Comment by caesiumstudio** [comment]
Not critical as it is installable from the pacman file, this issue will be taken care later.
