### ISSUE TITLE
Importing causes a massive memory+swap usage spike followed by a crash

### ISSUE THREAD

**Issue by xandark** [caesiumstudio/csBooks-updates#3]
After doing `snap run csbooks` for its first run and it asking me to import my library, I did so and then I noticed that the memory was being gobbled up and my machine started to not be responsive. Then csbooks terminated with this message at the console:

`fish: “snap run csbooks” terminated by signal SIGKILL (Forced quit)`

So it looks like the snap daemon noticed it was taking all of the system memory and killed it.

Here's my system monitor:

![Importing impact on my system 2](https://user-images.githubusercontent.com/5048913/101308979-016ce000-3800-11eb-966b-00a20e90c293.png)

Notice that impressive memory rollercoaster curve.

I have a 8GB machine, so resources can get exhausted pretty quickly.

**Comment by kerolloz** [comment]
Same issue here.. 5GB of RAM! 🤯 ![image](https://user-images.githubusercontent.com/36763164/104023280-186d6c00-51ca-11eb-9e4e-787b354af6b8.png)

**Comment by caesiumstudio** [comment]
Hey @kerolloz thank you for reporting this.. I am working to fix it now.

**Comment by caesiumstudio** [comment]
The issue was fixed in release 5.1.1 
https://github.com/caesiumstudio/csBooks-updates/releases/tag/5.5.1

@kerolloz @xandark Could you guys please confirm the fix, when you have time.
