### ISSUE TITLE
Truncated epub pages

### ISSUE THREAD

**Issue by fiorellabgs** [caesiumstudio/csBooks-updates#4]
Hello, since the last version of csBooks (4.3.0), every page of epubs I read is truncated. I can't read the lower part. I tried increasing and decreasing the font size but the result is still the same. 

![Screenshot](https://user-images.githubusercontent.com/37887664/101698717-49973700-3a7a-11eb-89bf-86ed6ae63690.png)

I don't know if someone else has encounter the same issue.

**Comment by caesiumstudio** [comment]
Hey Fiorella, 
Thank you for reporting the issue. I will have a look today and possibly fix it.

**Comment by caesiumstudio** [comment]
Hey Fiorella,
Could you please also tell me which Operating System are you using? Is it Windows or Linux?

**Comment by fiorellabgs** [comment]
Thank you for taking time to look into this issue ! 
I'm using Ubuntu 20.04.1.

**Comment by caesiumstudio** [comment]
Please do "snap refresh" OR download here
https://github.com/caesiumstudio/csBooks-updates/releases/tag/4.3.2
