### ISSUE TITLE
Important features request

### ISSUE THREAD

**Issue by tonypachino** [caesiumstudio/csBooks-updates#5]
i would like to suggest a very important features for every reader, features that are on iBooks on iPad, iPhone, macos, and kindle, highlight the text, and make the comment about highlighted text and option that we can export highlights and comments into the text file. 

These are a very important features when you reading a book.

**Comment by caesiumstudio** [comment]
Thank you for creating the feature request :)

**Comment by caesiumstudio** [comment]
Feature added in release 5.7.0 
For epub books persistant annotations are available now. 
- Adding annotations (user comment) on selecting text in the book
- All annotations are visible in the left sliding menu
- Export of annotations to text file 

@tonypachino It would be helpful If you could try the feature.
