### ISSUE TITLE
Dark mode disappearance

### ISSUE THREAD

**Issue by fiorellabgs** [caesiumstudio/csBooks-updates#6]
Hello @caesiumstudio,

The dark mode feature to read a book has disappeared, even Ctrl + n doesn't work anymore.

![Capture d’écran de 2021-01-15](https://user-images.githubusercontent.com/37887664/104779235-0322af80-577f-11eb-8ee6-73a1cece2542.png)

 I'm using Ubuntu 20.04.1.

**Comment by caesiumstudio** [comment]
Hey fiorellabgs, 
Thank you for reporting the issue. 
In the version 5.6.0 the dark mode has moved to the themes menu. 
The small icon in the top right corner. 
![image](https://user-images.githubusercontent.com/46374776/104781861-8d6d1280-5783-11eb-9329-f7fc3a53ab0b.png)
