### ISSUE TITLE
access to removable-media or partitions

### ISSUE THREAD

**Issue by gpf70sax** [caesiumstudio/csBooks-updates#7]
Hi, it's seems impossible to read files from removable-media or other partitions with ubuntu version.
I try to see which plugs are available for csBooks but I din't find "media" or "removable-media" to use with the "snap connect" command.
There is some other tricks or can you fix this?
Thanks Gianpiero.

**Comment by gpf70sax** [comment]
Great, thank you!
Bye Gianpiero

**Comment by caesiumstudio** [comment]
Fixed in release 5.6.1, added plug removable-media.
To access removable media, execute on terminal -

> snap connect csbooks:removable-media

@gpf70sax It would be helpful if you could test it on your system and confirm the fix. :)

**Comment by gpf70sax** [comment]
I will do, when it will be available?

**Comment by caesiumstudio** [comment]
Could you please check if you can access USB flash drive?

**Comment by gpf70sax** [comment]
yes, USB flash works fine!

**Comment by gpf70sax** [comment]
Ok, after the snap connection command the solution is to mount the partition (in my case) /Dati under /media/Dati, so it works !
Thank you
Bye Gianpiero.

**Comment by caesiumstudio** [comment]
Great! 
Your idea is also confirmed by this thread - https://forum.snapcraft.io/t/libreoffice-snap-cant-find-my-other-hard-disk/6456

**Comment by gpf70sax** [comment]
ok, now I fix it in fstab, so it mount automatically at start, but i don't know where and when make the "snap connect" ...
